version: "3"
services:
  react-image:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-image
    networks:
      - mern-stack-net
    volumes:
      - ./fronted/src:/usr/app/src
      - ./fronted/public:/usr/app/public
    depends_on:
      - my-express-app
    stdin_open: true
    tty: true

  my-express-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: my-express-app
    networks:
      - mern-stack-net
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
